//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacacionesRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePosition { get; set; }
        public string EmployeeDepto { get; set; }
        public Nullable<int> EmployeeDeptoId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Location { get; set; }
        public string BankAccount { get; set; }
        public string Identification { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
