//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacacionesRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDay
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int CurrentYear { get; set; }
        public int TotalDays { get; set; }
        public Nullable<int> TakenDays { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
