//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacacionesRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> Sender { get; set; }
        public string SenderEmail { get; set; }
        public string Message { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<int> ReceiverEmployeeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
