//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacacionesRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int Id { get; set; }
        public System.Guid IdHash { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> DeptoId { get; set; }
        public string Status { get; set; }
        public int DaysTaken { get; set; }
        public int DaysAvailable { get; set; }
        public int DaysRequested { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string AcceptedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> AcceptedRRHHDate { get; set; }
        public string AcceptedRRHHBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
